### ISSUE TITLE
Create docker container cluster for SWS API integrated tests

### ISSUE THREAD

**Issue by bkline** [NCIOCPL/sitewide-search-api#45]
*Create docker containers for ElasticSearch 5.6 server and SWS API server so we can perform integration tests against those servers.*

**Parent Issue:** #39 

### Sub-Tasks
- [x] Create `Dockerfile` for ElasticSearch server
- [x] Create `Dockerfile` for API server
- [x] Create `docker-compose.yml` file for cluster
- [x] Write instructions for building/rebuilding the cluster
- [x] Verify that the instructions work

### Notes
* Source code and build commands for the API will need to be copied into the `api` container.
* ElasticSearch configuration files (mustache scripts and `synonym.txt`) must be copied into the `elasticsearch` container.
* Expose port 9200 from the `elasticsearch` container.
* Expose port 5000 from the `api` container.
* Modifications to upgrade for ElasticSearch 7.9 will be part of another sprint.

**Comment by blairlearn** [comment]
Closed by a917bbf5d00cecf0b33e99e773f2861a2fe3a502
PR #46
