### ISSUE TITLE
Create and populate ElasticSearch indices for integrated tests

### ISSUE THREAD

**Issue by bkline** [NCIOCPL/sitewide-search-api#47]
*Load records pulled from the production `cgov` and `autosg` indices into the Docker `elasticsearch` container used for integrated testing.*

**Parent Issue:** #39

### Sub-Tasks
- [x] Install mapping and data files extracted from production ElasticSearch 5.6 server
- [x] Write the script for creating the indices and loading the data into the Docker ElasticSearch container
- [x] Write instructions for running the script
- [x] Verify that the instructions work

### Notes

* Mappings/settings files and bulk loading files were pulled as part of issue #40.

**Comment by blairlearn** [comment]
Closed by 8d82f1e666ef60691cb4eaa1f968f051fa0416c0
PR #49
