### ISSUE TITLE
Create integration tests for Search and Autosuggest features

### ISSUE THREAD

**Issue by bkline** [NCIOCPL/sitewide-search-api#48]
*Write gherkin tests to be run with `karate` for verifying expected behavior of the SWS APIs.*

**Parent Issue:** #39 

### Sub-Tasks
- [x] Create tests for the Search feature
- [x] Create tests for the Autosuggest feature
- [x] Write instructions for running the tests
- [x] Verify that the instructions work

### Notes

The Search tests should include:
* verification that the feature is available
* searches for English terms
* searches for Spanish terms
* searches against the `cgov` collection
* searches against the `doc` collection
* searches for terms containing spaces
* confirmation that case is ignored by the Search feature
* confirmation that diacritics are ignored by Search matching
* confirmation that searches against the `cgov` collection ignore the `site` parameter
* confirmation that searches against the `doc` collection only return results for the specified `site`
* confirmation that specifying an unsupported `language` value results in a 400 error
* confirmation that the `from` parameter defaults to 0
* confirmation that the `size` parameter defaults to 10
* confirmation that providing an explicit `from` parameter is honored
* confirmation that providing an explicit `size` parameter is honored

The Autosuggest tests should include:
* verification that the feature is available
* requests for matching English terms
* requests for matching Spanish terms
* requests whose `term`s consist of punctuation
* requests whose `term`s consist of decimal digits
* requests whose `term`s include punctuation and non-punctuation
* requests whose `term`s include decimal digits and non-digits
* confirmation that specifying an unsupported `language` value results in a 400 error
* confirmation that specifying an empty `term` results in a 400 error
* confirmation that case is ignored by the Autosuggest feature
* confirmation that diacritics are ignored by the Autosuggest feature

When the bug reported by https://github.com/NCIOCPL/sitewide-search-api/issues/43 has been fixed, tests will be added to confirm that specifying an unsupported collection results in a 400 error.
