### ISSUE TITLE
Enabler: Remove dependency on ES templates

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/sitewide-search-api#58]
# Refactor to use queries in the middle tier instead of calling specific query templates.

**Background:** The current implementation of sitewide search pushes all of the logic for the search queries into Elasticsearch, taking a template file as the first argument (`collection`) of the business logic (GET) routes of the controllers.

Specific tasks to be accomplished are:

- [ ] Refactor the controllers to introduce a Service layer which queries Elasticsearch.
- [ ] Implement queries in the Service layer, corresponding to those in the templates [see wiki](https://github.com/NCIOCPL/sitewide-search-api/wiki/Elasticsearch-Queries-for-SiteWide-Search-API).
- [ ] Change from synchronous calls to asynchronous.

This issue is a successor to #27.

> **ESTIMATE** 8

### Resources:
* [Template queries in the SWS wiki](https://github.com/NCIOCPL/sitewide-search-api/wiki/Elasticsearch-Queries-for-SiteWide-Search-API)

### Prerequisites
- 

### Sub-Tasks
-

**Comment by blairlearn** [comment]
@lburack  I need acceptance criteria.

What are a set of search criteria, and how many results, such that (A) you would consider the current set of results "correct" and (B) if the results remain unchanged, you would consider any changes to the API to also be "correct"?
